name: Build & test
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
            - run: npm install -g npm@latest
            - run: sudo apt-get update && sudo apt-get install -y cmake
            - run: npm install --unsafe-perm
            - run: npm test
